apiVersion: v1
kind: Pod
metadata:
  namespace: ansible-tower
spec:
  containers:
    - image: 'registry.redhat.io/ansible-tower-37/ansible-runner-rhel7'
      tty: true
      stdin: true
      imagePullPolicy: IfNotPresent
      args:
        - sleep
        - infinity
