apiVersion: v1
kind: Pod
metadata:
  namespace: ansible-tower
spec:
  containers:
    - image: 'quay.io/colin_mccarthy/pysnow_pod:latest'
      tty: true
      stdin: true
      imagePullPolicy: Always
      args:
        - sleep
        - infinity
