apiVersion: v1
kind: Pod
metadata:
  namespace: ansible-tower
spec:
  containers:
    - image: 'quay.io/ansible-tower/ansible-runner:1.4.4'
      tty: true
      stdin: true
      imagePullPolicy: Always
      args:
        - sleep
        - infinity
