FROM quay.io/colin_mccarthy/ansible-runner:stable_1.4.x


# Securing the Pod
RUN dnf -y update && \
    rm -rf /var/cache/dnf


# dependencies 
RUN pip3 install --no-cache-dir pysnow


# required
CMD ["ansible-runner", "run", "/runner"]
